'use strict';

/*
 * Template signatures: Ed25519, domain separated, no algorithm field.
 *
 * ⚠️ A DEDICATED KEY, AND DELIBERATELY NOT THE SUPPORT KEY. lib/support-access.js is built on the
 * rule "a key we hold must not be a key to every install": a support token is useless without a
 * request code the customer's own server minted, and its private key lives on the hosted server
 * because that is where tokens are issued. A catalog key is the opposite shape — its signature
 * alone is what lets a template's code onto every screen whose owner switched the library on — so
 * it has to be the key that lives OFFLINE, on the maintainer's machine, used by
 * scripts/template-catalog.js and nothing else. Sharing one key would give the internet-facing
 * support signer the power to publish code, and would make rotating either one rotate both.
 *
 * ⚠️ DOMAIN SEPARATION. Every signed message is prefixed with a context line, so a signature made
 * for one purpose can never verify as another: a package signature is not an index signature, and
 * neither is a support token (whose own prefix is STSUP1), even under the same key.
 */

const crypto = require('crypto');

const PACKAGE_CONTEXT = 'screenforge-template-package/1\n';
const INDEX_CONTEXT = 'screenforge-template-index/1\n';

/*
 * The official Kardinal Screens template catalog key. The private half is generated by
 * `node scripts/template-catalog.js keygen` and kept offline (see catalog/SIGNING.md).
 */
const OFFICIAL_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAunvHHUilBsMzl3MhnzcBmQ6EKgQ1KfuSpyUCAgCY3HY=
-----END PUBLIC KEY-----
`;

/*
 * ⚠️ SMALL-ORDER KEYS ARE REFUSED. Node accepts the identity point (and the other points of
 * order 1, 2, 4 and 8) as an Ed25519 public key, and for the identity the signature
 * `01 00…00 ‖ 00×32` verifies for EVERY message — so a catalog added with such a key would
 * "verify" anything anyone signs. These are the libsodium blocklist encodings; the top (sign) bit
 * is masked so each point's alternate encoding is caught too.
 */
const SMALL_ORDER = [
  '0100000000000000000000000000000000000000000000000000000000000000',
  '0000000000000000000000000000000000000000000000000000000000000000',
  'ecffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f',
  'c7176a703d4dd84fba3c0b760d10670f2a2053fa2c39ccc64ec7fd7792ac037a',
  '26e8958fc2b227b045c3f489f2ef98f0d5dfac05d3c63339b13802886d53fc05',
  'edffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f',
  'eeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f',
];
function isSmallOrder(raw) {
  const masked = Buffer.from(raw);
  masked[31] &= 0x7f;
  return SMALL_ORDER.includes(masked.toString('hex'));
}

function toPublicKey(pemOrKey) {
  const key = typeof pemOrKey === 'string'
    ? crypto.createPublicKey(pemOrKey.replace(/\\n/g, '\n'))
    : pemOrKey;
  if (!key || key.type !== 'public' || key.asymmetricKeyType !== 'ed25519') throw new Error('catalog key must be an Ed25519 public key');
  const der = key.export({ type: 'spki', format: 'der' });
  if (isSmallOrder(der.subarray(der.length - 32))) throw new Error('catalog key is a weak (small-order) Ed25519 point');
  return key;
}

function rawPublicKey(key) {
  // SPKI for Ed25519 is a fixed 12-byte header followed by the 32-byte key.
  const der = toPublicKey(key).export({ type: 'spki', format: 'der' });
  return der.subarray(der.length - 32);
}

/** Short, stable identifier for a public key: first 16 hex of sha256(raw key). */
function keyId(key) {
  return crypto.createHash('sha256').update(rawPublicKey(key)).digest('hex').slice(0, 16);
}

function officialPublicKey() {
  return toPublicKey(process.env.TEMPLATE_CATALOG_PUBLIC_KEY || OFFICIAL_PUBLIC_KEY_PEM);
}

function loadPrivateKey(pem) {
  const key = crypto.createPrivateKey(pem);
  if (key.asymmetricKeyType !== 'ed25519') throw new Error('catalog signing key must be Ed25519');
  return key;
}

function signPackage(packageBytes, privateKey) {
  const pub = crypto.createPublicKey(privateKey);
  return {
    key_id: keyId(pub),
    sig: crypto.sign(null, Buffer.concat([Buffer.from(PACKAGE_CONTEXT), packageBytes]), privateKey),
  };
}

function signIndex(indexBytes, privateKey) {
  const pub = crypto.createPublicKey(privateKey);
  return { key_id: keyId(pub), sig: crypto.sign(null, Buffer.concat([Buffer.from(INDEX_CONTEXT), indexBytes]), privateKey) };
}

function verifyWith(context, bytes, sig, key) {
  try {
    return crypto.verify(null, Buffer.concat([Buffer.from(context), bytes]), toPublicKey(key), sig);
  } catch {
    return false;
  }
}

/**
 * Which trusted key (if any) signed this package.
 * `trusted` = [{ id, label, key }] — the caller decides which catalogs are trusted.
 * Returns the matching entry or null. Never throws.
 */
function verifyPackage(packageBytes, signature, trusted) {
  if (!signature || !signature.sig) return null;
  for (const t of trusted || []) {
    let kid;
    try { kid = keyId(t.key); } catch { continue; }
    if (kid !== signature.key_id) continue;
    if (verifyWith(PACKAGE_CONTEXT, packageBytes, signature.sig, t.key)) return t;
  }
  return null;
}

/** Index signature file: `<key_id>:<base64 sig>\n`. */
function formatIndexSignature({ key_id, sig }) {
  return `${key_id}:${Buffer.from(sig).toString('base64')}\n`;
}

function parseIndexSignature(text) {
  const m = /^([0-9a-f]{16}):([A-Za-z0-9+/]{86}==)\s*$/.exec(String(text || ''));
  if (!m) return null;
  return { key_id: m[1], sig: Buffer.from(m[2], 'base64') };
}

function verifyIndex(indexBytes, sigText, key) {
  const s = parseIndexSignature(sigText);
  if (!s) return false;
  let kid;
  try { kid = keyId(key); } catch { return false; }
  if (kid !== s.key_id) return false;
  return verifyWith(INDEX_CONTEXT, indexBytes, s.sig, key);
}

module.exports = {
  PACKAGE_CONTEXT, INDEX_CONTEXT, OFFICIAL_PUBLIC_KEY_PEM,
  toPublicKey, keyId, officialPublicKey, loadPrivateKey,
  signPackage, signIndex, verifyPackage, verifyIndex, isSmallOrder,
  formatIndexSignature, parseIndexSignature,
};
